config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  post '/afterpay', :to => "afterpay#checkout", :as => :afterpay_checkout
  resources :afterpay, only: [] do
    member do
      get :success
      get :cancel
    end
  end

  namespace :admin do
    resources :orders, only: [] do
      resources :payments, only: [] do
        member do
          get 'afterpay_refund'
          post 'execute_afterpay_refund'
        end
      end
    end
  end

end

app/views/spree/admin/payments/afterpay_refund.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Payments' } %>

<% content_for :page_title do %>
    / <%= link_to Spree.t(:payments), admin_order_payments_path(@order) %>
    / <%= payment_method_name(@payment) %>
    / <%= Spree.t('refund', scope: :afterpay) %>
<% end %>

<%= form_tag execute_afterpay_refund_admin_order_payment_path(@order, @payment) do %>
  <div class="label-block left five columns alpha">
    <div>
      <fieldset data-hook="admin_variant_new_form">
        <legend><%= Spree.t('refund', scope: :afterpay) %></legend>
        <div class='form-group'>
          <%= label_tag 'refund_amount', Spree.t(:refund_amount, scope: :afterpay) %>
          <small><em><%= Spree.t(:original_amount, scope: :afterpay, :amount => @payment.display_amount) %></em></small><br>
        </div>

        <% currency = ::Money::Currency.new(@payment.currency) %>
        <div class="form-group">
          <div class="input-group">
            <% if currency.symbol_first %>
                <span class="input-group-addon" id="basic-addon1"><%= currency.symbol %></span>
                <%= text_field_tag 'refund_amount', @payment.amount, class: 'form-control' %>
            <% else %>
                <%= text_field_tag 'refund_amount', @payment.amount, class: 'form-control' %>
                <span class="input-group-addon" id="basic-addon1"><%= currency.symbol %></span>
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= label_tag :refund_reason_id, Spree.t(:reason) %><br/>
          <%= select_tag(:refund_reason_id, options_from_collection_for_select(Spree::RefundReason.active.all, :id, :name), {class: 'select2'}) %>
        </div>

        <div class="form-group">
          <%= button Spree.t(:refund, scope: :afterpay), class: 'btn btn-primary' %>
        </div>
      </fieldset>
    </div>
  </div>
<% end %>